### ISSUE TITLE
"ValueError: not enough values to unpack (expected 2, got 1)" occurs when I run ``mustached-bear/update``

### ISSUE THREAD

**Issue by masayukig** [jogo/mustached-bear#2]
When I run ``mustached-bear/update``, an error occurs recently.
I suppose the reason is some of entries of the response of ``requests.get("https://review.openstack.org:443/projects/")`` doesn't have ``/``. They are ``API-Projects``, ``All-Projects`` and ``All-Users``. I think we should care about that.

```
$ ./mustached-bear/update
Traceback (most recent call last):
  File "./mustached-bear/update", line 52, in _split_org_name
    org, name = self.full_name.split('/')
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./mustached-bear/update", line 275, in <module>
    main(args.force, args.delete, args.concurrency)
  File "./mustached-bear/update", line 237, in main
    projects.append(Project(name))
  File "./mustached-bear/update", line 47, in __init__
    self.org, self.name = self._split_org_name()
  File "./mustached-bear/update", line 54, in _split_org_name
    print("Unable to split '%s' on '/'" % self.project)
AttributeError: 'Project' object has no attribute 'project'
```

**Comment by masayukig** [comment]
And I found that accessing to ``self.project`` in the Project class is also a bug.
